version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network
    volumes:
      - ./mysql:/var/lib/mysql

  node:
    build: 
      context: ./node
    container_name: node
    restart: always
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - my-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 8080:80
    networks:
      - my-network
    depends_on:
      - node

networks:
  my-network:
    driver: bridge